/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hasan.derskayit.view;

import com.hasan.derskayit.entity.FacultyMember;
import com.hasan.derskayit.entity.FacultyMemberLectures;
import com.hasan.derskayit.entity.Student;
import com.hasan.derskayit.service.FacultyMemberLecturesService;
import com.hasan.derskayit.service.FacultyMemberService;
import com.hasan.derskayit.service.StudentService;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hasan
 */
public class frmFacultyMember extends javax.swing.JFrame {

    /**
     * Creates new form frmFacultyMember
     */
    public frmFacultyMember() {
        initComponents();
        tabloDoldur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtAd = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKod = new javax.swing.JTextField();
        txtSoyad = new javax.swing.JTextField();
        dateBaslangicTarihi = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoca = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id");

        jLabel2.setText("Ad");

        jLabel3.setText("Email");

        txtId.setEditable(false);

        jLabel4.setText("Kod");

        jLabel5.setText("Soyad");

        jLabel6.setText("Başl. Tar.");

        jButton1.setText("Sil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Yeni");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Kaydet");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tblHoca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHoca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHocaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoca);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(txtAd)
                            .addComponent(txtId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addGap(12, 12, 12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtSoyad, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                        .addComponent(txtKod)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dateBaslangicTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtKod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(dateBaslangicTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //TODO baslangıç tarihi format String kalıyor
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        DateFormat sdf = new SimpleDateFormat("yyyy-MM-dd  HH:MM:SS");
        String baslangicTarihi = sdf.format(dateBaslangicTarihi.getDate());
        String ad = txtAd.getText();
        String soyad = txtSoyad.getText();
        String kod = txtKod.getText();
        String email = txtEmail.getText();

        FacultyMember facultyMember = new FacultyMember();

        facultyMember.setCode(kod);
        facultyMember.setEmail(email);
        facultyMember.setName(ad);
        facultyMember.setSurname(soyad);
        facultyMember.setCreated_at(new Date());
        //    facultyMember.setStartDate(Date.parse(baslangicTarihi));

        FacultyMemberService facultyMemberService = new FacultyMemberService();
        if (!txtId.getText().equals("")) {
            facultyMemberService.save(facultyMember);
            JOptionPane.showMessageDialog(this, "Öğrenci Başarıyla Eklendi.");
        } else {
            facultyMember.setId(Long.valueOf(txtId.getText()));
            facultyMemberService.update(facultyMember);
            JOptionPane.showMessageDialog(this, "Öğrenci Başarıyla Güncellendi.");
        }
        formTemizle();
        tabloDoldur();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        formTemizle();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblHocaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHocaMouseClicked
        if (tblHoca.getSelectedRow() != -1) {
            Long Id = Long.valueOf(tblHoca.getModel().getValueAt(tblHoca.getSelectedRow(), 0).toString());
            String kod = tblHoca.getModel().getValueAt(tblHoca.getSelectedRow(), 1).toString();
            String name = tblHoca.getModel().getValueAt(tblHoca.getSelectedRow(), 2).toString();
            String surname = tblHoca.getModel().getValueAt(tblHoca.getSelectedRow(), 3).toString();
            String email = tblHoca.getModel().getValueAt(tblHoca.getSelectedRow(), 4).toString();
            String baslangicTarihi = tblHoca.getModel().getValueAt(tblHoca.getSelectedRow(), 5).toString();

            txtAd.setText(name);
            txtSoyad.setText(surname);
            txtKod.setText(kod);
            txtId.setText(String.valueOf(Id));
            txtEmail.setText(email);
          //  dateBaslangicTarihi.setDate(Date.parse(baslangicTarihi.));
        }
    }//GEN-LAST:event_tblHocaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (!txtId.getText().equals("")) {
            Long id = Long.valueOf(txtId.getText());
            FacultyMember s = new FacultyMember();
            s.setId(id);
            s.setCode(txtKod.getText());
            s.setName(txtAd.getText());
            s.setSurname(txtSoyad.getText());
            s.setEmail(txtEmail.getText());
            new FacultyMemberService().delete(s);
            JOptionPane.showMessageDialog(this, "Hoca Başarıyla Silindi.");
            formTemizle();
            tabloDoldur();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFacultyMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFacultyMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFacultyMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFacultyMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFacultyMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateBaslangicTarihi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHoca;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtKod;
    private javax.swing.JTextField txtSoyad;
    // End of variables declaration//GEN-END:variables

    private void tabloDoldur() {
        List<FacultyMember> fm = new FacultyMemberService().getAll();
        String[] columnNames = new String[7];
        columnNames[0] = "Id";
        columnNames[1] = "Kod";
        columnNames[2] = "Adı";
        columnNames[3] = "Soyadı";
        columnNames[4] = "Email";
        columnNames[5] = "Baş. Tar.";
        columnNames[6] = "Oluş. Tar.";
        String[][] data = new String[fm.size()][7];
        for (int i = 0; i < fm.size(); i++) {
            FacultyMember ft = fm.get(i);
            data[i][0] = ft.getId().toString();
            data[i][1] = ft.getCode();
            data[i][2] = ft.getName();
            data[i][3] = ft.getSurname();
            data[i][4] = ft.getEmail();
            data[i][5] = "";
            data[i][6] = "";
            if (null != (ft.getStartDate())) {
                data[i][5] = ft.getStartDate().toLocaleString();
            }
            if (null != (ft.getCreated_at())) {
                data[i][6] = ft.getCreated_at().toLocaleString();
            }
        }
        tblHoca.setModel(new DefaultTableModel(data, columnNames));
    }

    private void formTemizle() {
        txtAd.setText("");
        txtSoyad.setText("");
        txtKod.setText("");
        txtId.setText("");
        txtEmail.setText("");
        dateBaslangicTarihi.setDate(null);
    }
}
